server:
 port: 8082
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/journal_db
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    server:
      url: http://localhost:8080/journal-service
