eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
  instance:
    prefer-ip-address: true
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/user_db
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /user-docs/v3/api-docs
